# Generated by Django 5.0.6 on 2024-07-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('github_username', models.CharField(max_length=256, unique=True)),
                ('github_token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ReadmeFile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadmeBuilderWebApp0.user')),
            ],
        ),
    ]
