# Generated by Django 5.0.6 on 2024-07-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadmeBuilderWebApp0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/media/default.png', upload_to=''),
        ),
    ]
