# Generated by Django 5.0.6 on 2024-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadmeBuilderWebApp0', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='images/'),
        ),
    ]
